-- Run this SQL in Supabase SQL Editor
create extension if not exists "pgcrypto";

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  slug text not null unique,
  description text,
  icon text,
  parent_id bigint references public.categories(id) on delete set null,
  created_at timestamptz not null default now()
);

alter table public.categories add column if not exists description text;
alter table public.categories add column if not exists icon text;
alter table public.categories add column if not exists parent_id bigint references public.categories(id) on delete set null;

create table if not exists public.users (
  id uuid primary key,
  name text,
  email text unique not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.admins (
  id uuid primary key,
  name text not null,
  email text unique not null,
  password text not null,
  is_admin boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.wallpapers (
  id uuid primary key default gen_random_uuid(),
  filename text unique,
  title text not null,
  description text,
  image_url text not null,
  mime text,
  size bigint not null default 0,
  width integer not null default 0,
  height integer not null default 0,
  category_folder text,
  storage_path text not null unique,
  user_id uuid not null references auth.users(id) on delete cascade,
  views integer not null default 0,
  likes_count integer not null default 0,
  downloads integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.wallpapers add column if not exists filename text;
alter table public.wallpapers add column if not exists mime text;
alter table public.wallpapers add column if not exists size bigint not null default 0;
alter table public.wallpapers add column if not exists width integer not null default 0;
alter table public.wallpapers add column if not exists height integer not null default 0;
alter table public.wallpapers add column if not exists downloads integer not null default 0;
alter table public.wallpapers add column if not exists category_folder text;

create table if not exists public.wallpaper_categories (
  wallpaper_id uuid not null references public.wallpapers(id) on delete cascade,
  category_id bigint not null references public.categories(id) on delete cascade,
  primary key (wallpaper_id, category_id)
);

create table if not exists public.wallpaper_likes (
  id bigint generated by default as identity primary key,
  wallpaper_id uuid not null references public.wallpapers(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (wallpaper_id, user_id)
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  type text not null,
  title text not null,
  message text not null,
  wallpaper_id uuid references public.wallpapers(id) on delete set null,
  from_user_id uuid references auth.users(id) on delete set null,
  read boolean not null default false,
  created_at timestamptz not null default now()
);

insert into public.categories (name, slug)
values
  ('Nature', 'nature'),
  ('Technology', 'technology'),
  ('Anime', 'anime'),
  ('Cars', 'cars'),
  ('Minimal', 'minimal')
on conflict (slug) do nothing;

alter table public.categories enable row level security;
alter table public.users enable row level security;
alter table public.admins enable row level security;
alter table public.wallpapers enable row level security;
alter table public.wallpaper_categories enable row level security;
alter table public.wallpaper_likes enable row level security;
alter table public.notifications enable row level security;

-- Public read policies
drop policy if exists "public can read categories" on public.categories;
create policy "public can read categories"
  on public.categories
  for select
  using (true);

drop policy if exists "public can read users" on public.users;
create policy "public can read users"
  on public.users
  for select
  using (true);

drop policy if exists "public can read admins" on public.admins;
create policy "public can read admins"
  on public.admins
  for select
  using (false);

drop policy if exists "public can read wallpapers" on public.wallpapers;
create policy "public can read wallpapers"
  on public.wallpapers
  for select
  using (true);

drop policy if exists "public can read wallpaper category links" on public.wallpaper_categories;
create policy "public can read wallpaper category links"
  on public.wallpaper_categories
  for select
  using (true);

-- Authenticated write policies
drop policy if exists "authenticated can create wallpapers" on public.wallpapers;
create policy "authenticated can create wallpapers"
  on public.wallpapers
  for insert
  to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "owner can update own wallpapers" on public.wallpapers;
create policy "owner can update own wallpapers"
  on public.wallpapers
  for update
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "owner can delete own wallpapers" on public.wallpapers;
create policy "owner can delete own wallpapers"
  on public.wallpapers
  for delete
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "authenticated can link categories" on public.wallpaper_categories;
create policy "authenticated can link categories"
  on public.wallpaper_categories
  for insert
  to authenticated
  with check (true);

drop policy if exists "authenticated can like" on public.wallpaper_likes;
create policy "authenticated can like"
  on public.wallpaper_likes
  for insert
  to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "owner can unlike" on public.wallpaper_likes;
create policy "owner can unlike"
  on public.wallpaper_likes
  for delete
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "owner can read notifications" on public.notifications;
create policy "owner can read notifications"
  on public.notifications
  for select
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "owner can update notifications" on public.notifications;
create policy "owner can update notifications"
  on public.notifications
  for update
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "service role can insert notifications" on public.notifications;
create policy "service role can insert notifications"
  on public.notifications
  for insert
  to authenticated
  with check (auth.uid() = user_id);
